# Generated by Django 3.0.5 on 2020-04-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200419_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedmenu',
            old_name='name',
            new_name='menu',
        ),
    ]
