# Generated by Django 3.0.5 on 2020-04-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200419_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedmenu',
            name='taste',
            field=models.TextField(default='Regular', verbose_name='taste'),
        ),
    ]
