# Generated by Django 3.0.5 on 2020-04-19 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderedmenu_taste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_total', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total')),
                ('paid', models.BooleanField(verbose_name='Paid')),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='discount')),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Order')),
                ('menu', models.ManyToManyField(to='core.OrderedMenu', verbose_name='Ordered Menu')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Orders',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.AddField(
            model_name='billing',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Order', verbose_name='Order'),
        ),
    ]
